<?php

namespace Aisg\Sections;

/**
 * Template rules that keep JS and PHP output identical and keep the AI out of markup
 * (docs/ARCHITECTURE.md §4.3).
 */
final class TemplateLinter
{
    /**
     * Resolver-provided fields that may be emitted unescaped. Content fields never may.
     */
    public const UNESCAPED_ALLOWLIST = ['price_html'];

    /**
     * @return list<string>
     */
    public static function lint(string $template): array
    {
        $errors = [];

        if (preg_match('/\{\{\s*>/', $template)) {
            $errors[] = 'partials ({{> ...}}) are not allowed';
        }

        if (preg_match('/\{\{\s*=/', $template)) {
            $errors[] = 'set-delimiter tags are not allowed';
        }

        if (preg_match('/\{\{\s*&/', $template)) {
            $errors[] = 'unescaped {{& ...}} tags are not allowed; use the allowlisted {{{ }}} fields';
        }

        preg_match_all('/\{\{\{\s*([^}]+?)\s*\}\}\}/', $template, $matches);
        foreach ($matches[1] as $name) {
            $leaf = substr((string) strrchr('.'.$name, '.'), 1);

            if (! in_array($leaf, self::UNESCAPED_ALLOWLIST, true)) {
                $errors[] = "unescaped output of [{$name}] is not allowed";
            }
        }

        // Class tokens must be tw-*, aisg-* or a responsive/state variant of tw-*.
        // Plain class="" only; Alpine bindings (:class, x-bind:class) are expressions, not class lists.
        preg_match_all('/(?<![:\w-])class="([^"]*)"/', $template, $classAttributes);
        foreach ($classAttributes[1] as $attribute) {
            // Remove Mustache sections that toggle whole classes: {{#flag}}tw-x{{/flag}}
            $plain = preg_replace('/\{\{[#^\/][^}]*\}\}/', ' ', $attribute) ?? '';
            // Icon classes are the one allowed interpolation: values are enum-validated
            // against Icons::NAMES and the CSS is not generated by Tailwind.
            $plain = preg_replace('/aisg-icon--\{\{[^}]+\}\}/', 'aisg-icon--x', $plain) ?? '';

            if (str_contains($plain, '{{')) {
                $errors[] = "class attribute interpolates a variable: \"{$attribute}\" (use {{#style.x_is_y}}tw-...{{/style.x_is_y}})";

                continue;
            }

            foreach (preg_split('/\s+/', trim($plain)) ?: [] as $class) {
                if ($class === '') {
                    continue;
                }

                $base = substr((string) strrchr(':'.$class, ':'), 1);

                if (! str_starts_with($base, 'tw-') && ! str_starts_with($base, '-tw-') && ! str_starts_with($base, 'aisg-') && $base !== 'aisg') {
                    $errors[] = "class [{$class}] must use the tw- or aisg- prefix";
                }

                if (preg_match('/^-?tw-(ml|mr|pl|pr|left|right|text-left|text-right|rounded-l|rounded-r|border-l|border-r)(-|$)/', $base)) {
                    $errors[] = "class [{$class}] is a physical direction; use logical utilities (ms/me/ps/pe/start/end) for RTL";
                }
            }
        }

        return $errors;
    }
}
